# Server Config
server:
  port: 9191

# Trick to let IntelliJ view endpoints through actuator.
management:
  endpoints:
    jmx:
      exposure:
        include: "*"

# Database Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soccatech-db?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show_sql: true
    format_sql: true

# Encryption Configuration
encryption:
  salt:
    rounds: 10

